import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});

export type Database = {
  public: {
    Tables: {
      schools: {
        Row: {
          id: string;
          name: string;
          school_type: string | null;
          phone: string | null;
          email: string;
          address: string | null;
          state: string;
          city: string;
          country: string;
          logo_url: string | null;
          motto: string | null;
          founded_year: number | null;
          is_active: boolean;
          trial_ends_at: string | null;
          subscription_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          school_type?: string | null;
          phone?: string | null;
          email: string;
          address?: string | null;
          state: string;
          city: string;
          country?: string;
          logo_url?: string | null;
          motto?: string | null;
          founded_year?: number | null;
          is_active?: boolean;
          trial_ends_at?: string | null;
          subscription_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          school_type?: string | null;
          phone?: string | null;
          email?: string;
          address?: string | null;
          state?: string;
          city?: string;
          country?: string;
          logo_url?: string | null;
          motto?: string | null;
          founded_year?: number | null;
          is_active?: boolean;
          trial_ends_at?: string | null;
          subscription_status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      staff: {
        Row: {
          id: string;
          school_id: string;
          user_id: string | null;
          staff_id: string;
          full_name: string;
          email: string | null;
          phone: string;
          role: string;
          position: string | null;
          department: string | null;
          photo_url: string | null;
          pin: string | null;
          is_active: boolean;
          temporary_pin: string | null;
          pin_expires_at: string | null;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          user_id?: string | null;
          staff_id: string;
          full_name: string;
          email?: string | null;
          phone: string;
          role: string;
          position?: string | null;
          department?: string | null;
          photo_url?: string | null;
          pin?: string | null;
          is_active?: boolean;
          temporary_pin?: string | null;
          pin_expires_at?: string | null;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          user_id?: string | null;
          staff_id?: string;
          full_name?: string;
          email?: string | null;
          phone?: string;
          role?: string;
          position?: string | null;
          department?: string | null;
          photo_url?: string | null;
          pin?: string | null;
          is_active?: boolean;
          temporary_pin?: string | null;
          pin_expires_at?: string | null;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      students: {
        Row: {
          id: string;
          school_id: string;
          user_id: string | null;
          student_id: string;
          admission_number: string | null;
          first_name: string;
          last_name: string;
          middle_name: string | null;
          date_of_birth: string | null;
          gender: string | null;
          photo_url: string | null;
          address: string | null;
          state_of_origin: string | null;
          religion: string | null;
          blood_group: string | null;
          genotype: string | null;
          allergies: string | null;
          medical_conditions: string | null;
          class_id: string | null;
          admission_date: string | null;
          graduation_date: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          user_id?: string | null;
          student_id: string;
          admission_number?: string | null;
          first_name: string;
          last_name: string;
          middle_name?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          photo_url?: string | null;
          address?: string | null;
          state_of_origin?: string | null;
          religion?: string | null;
          blood_group?: string | null;
          genotype?: string | null;
          allergies?: string | null;
          medical_conditions?: string | null;
          class_id?: string | null;
          admission_date?: string | null;
          graduation_date?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          user_id?: string | null;
          student_id?: string;
          admission_number?: string | null;
          first_name?: string;
          last_name?: string;
          middle_name?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          photo_url?: string | null;
          address?: string | null;
          state_of_origin?: string | null;
          religion?: string | null;
          blood_group?: string | null;
          genotype?: string | null;
          allergies?: string | null;
          medical_conditions?: string | null;
          class_id?: string | null;
          admission_date?: string | null;
          graduation_date?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      parents: {
        Row: {
          id: string;
          school_id: string;
          user_id: string | null;
          father_name: string | null;
          father_phone: string | null;
          father_email: string | null;
          father_occupation: string | null;
          mother_name: string | null;
          mother_phone: string | null;
          mother_email: string | null;
          mother_occupation: string | null;
          guardian_name: string | null;
          guardian_phone: string | null;
          guardian_email: string | null;
          guardian_relationship: string | null;
          primary_phone: string | null;
          secondary_phone: string | null;
          email: string | null;
          address: string | null;
          is_active: boolean;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          user_id?: string | null;
          father_name?: string | null;
          father_phone?: string | null;
          father_email?: string | null;
          father_occupation?: string | null;
          mother_name?: string | null;
          mother_phone?: string | null;
          mother_email?: string | null;
          mother_occupation?: string | null;
          guardian_name?: string | null;
          guardian_phone?: string | null;
          guardian_email?: string | null;
          guardian_relationship?: string | null;
          primary_phone?: string | null;
          secondary_phone?: string | null;
          email?: string | null;
          address?: string | null;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          user_id?: string | null;
          father_name?: string | null;
          father_phone?: string | null;
          father_email?: string | null;
          father_occupation?: string | null;
          mother_name?: string | null;
          mother_phone?: string | null;
          mother_email?: string | null;
          mother_occupation?: string | null;
          guardian_name?: string | null;
          guardian_phone?: string | null;
          guardian_email?: string | null;
          guardian_relationship?: string | null;
          primary_phone?: string | null;
          secondary_phone?: string | null;
          email?: string | null;
          address?: string | null;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      classes: {
        Row: {
          id: string;
          school_id: string;
          name: string;
          grade_level: string;
          section: string | null;
          capacity: number;
          class_teacher_id: string | null;
          academic_session_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          name: string;
          grade_level: string;
          section?: string | null;
          capacity?: number;
          class_teacher_id?: string | null;
          academic_session_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          name?: string;
          grade_level?: string;
          section?: string | null;
          capacity?: number;
          class_teacher_id?: string | null;
          academic_session_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      subjects: {
        Row: {
          id: string;
          school_id: string;
          name: string;
          code: string | null;
          description: string | null;
          curriculum_type: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          name: string;
          code?: string | null;
          description?: string | null;
          curriculum_type?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          name?: string;
          code?: string | null;
          description?: string | null;
          curriculum_type?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      attendance: {
        Row: {
          id: string;
          school_id: string;
          student_id: string;
          class_id: string | null;
          academic_term_id: string | null;
          date: string;
          status: string;
          marked_by: string | null;
          remarks: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          student_id: string;
          class_id?: string | null;
          academic_term_id?: string | null;
          date: string;
          status: string;
          marked_by?: string | null;
          remarks?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          student_id?: string;
          class_id?: string | null;
          academic_term_id?: string | null;
          date?: string;
          status?: string;
          marked_by?: string | null;
          remarks?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      grades: {
        Row: {
          id: string;
          school_id: string;
          student_id: string;
          class_id: string | null;
          subject_id: string;
          academic_term_id: string;
          assessment_type: string | null;
          score: number | null;
          max_score: number;
          grade: string | null;
          remarks: string | null;
          entered_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          student_id: string;
          class_id?: string | null;
          subject_id: string;
          academic_term_id: string;
          assessment_type?: string | null;
          score?: number | null;
          max_score?: number;
          grade?: string | null;
          remarks?: string | null;
          entered_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          student_id?: string;
          class_id?: string | null;
          subject_id?: string;
          academic_term_id?: string;
          assessment_type?: string | null;
          score?: number | null;
          max_score?: number;
          grade?: string | null;
          remarks?: string | null;
          entered_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      behaviour_records: {
        Row: {
          id: string;
          school_id: string;
          student_id: string;
          class_id: string | null;
          staff_id: string | null;
          date: string;
          behaviour_type: string;
          category: string | null;
          description: string;
          points: number;
          action_taken: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          student_id: string;
          class_id?: string | null;
          staff_id?: string | null;
          date: string;
          behaviour_type: string;
          category?: string | null;
          description: string;
          points?: number;
          action_taken?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          student_id?: string;
          class_id?: string | null;
          staff_id?: string | null;
          date?: string;
          behaviour_type?: string;
          category?: string | null;
          description?: string;
          points?: number;
          action_taken?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      risk_assessments: {
        Row: {
          id: string;
          school_id: string;
          student_id: string;
          academic_term_id: string | null;
          risk_score: number | null;
          risk_level: string | null;
          attendance_score: number | null;
          academic_score: number | null;
          behaviour_score: number | null;
          payment_score: number | null;
          assignment_score: number | null;
          factors: Record<string, unknown> | null;
          recommendations: Record<string, unknown> | null;
          assessed_at: string;
          next_assessment_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          student_id: string;
          academic_term_id?: string | null;
          risk_score?: number | null;
          risk_level?: string | null;
          attendance_score?: number | null;
          academic_score?: number | null;
          behaviour_score?: number | null;
          payment_score?: number | null;
          assignment_score?: number | null;
          factors?: Record<string, unknown> | null;
          recommendations?: Record<string, unknown> | null;
          assessed_at?: string;
          next_assessment_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          student_id?: string;
          academic_term_id?: string | null;
          risk_score?: number | null;
          risk_level?: string | null;
          attendance_score?: number | null;
          academic_score?: number | null;
          behaviour_score?: number | null;
          payment_score?: number | null;
          assignment_score?: number | null;
          factors?: Record<string, unknown> | null;
          recommendations?: Record<string, unknown> | null;
          assessed_at?: string;
          next_assessment_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      interventions: {
        Row: {
          id: string;
          school_id: string;
          student_id: string;
          risk_assessment_id: string | null;
          counselor_id: string | null;
          intervention_type: string | null;
          title: string;
          description: string | null;
          status: string;
          priority: string;
          start_date: string | null;
          end_date: string | null;
          outcomes: string | null;
          parent_notified: boolean;
          parent_notification_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          student_id: string;
          risk_assessment_id?: string | null;
          counselor_id?: string | null;
          intervention_type?: string | null;
          title: string;
          description?: string | null;
          status?: string;
          priority?: string;
          start_date?: string | null;
          end_date?: string | null;
          outcomes?: string | null;
          parent_notified?: boolean;
          parent_notification_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          student_id?: string;
          risk_assessment_id?: string | null;
          counselor_id?: string | null;
          intervention_type?: string | null;
          title?: string;
          description?: string | null;
          status?: string;
          priority?: string;
          start_date?: string | null;
          end_date?: string | null;
          outcomes?: string | null;
          parent_notified?: boolean;
          parent_notification_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          school_id: string;
          user_id: string | null;
          recipient_type: string | null;
          recipient_id: string | null;
          notification_type: string | null;
          title: string;
          message: string | null;
          data: Record<string, unknown> | null;
          is_read: boolean;
          read_at: string | null;
          sent_via: Record<string, unknown> | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          user_id?: string | null;
          recipient_type?: string | null;
          recipient_id?: string | null;
          notification_type?: string | null;
          title: string;
          message?: string | null;
          data?: Record<string, unknown> | null;
          is_read?: boolean;
          read_at?: string | null;
          sent_via?: Record<string, unknown> | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          user_id?: string | null;
          recipient_type?: string | null;
          recipient_id?: string | null;
          notification_type?: string | null;
          title?: string;
          message?: string | null;
          data?: Record<string, unknown> | null;
          is_read?: boolean;
          read_at?: string | null;
          sent_via?: Record<string, unknown> | null;
          created_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          school_id: string;
          plan: string;
          billing_cycle: string | null;
          amount: number;
          currency: string;
          start_date: string;
          end_date: string | null;
          status: string;
          max_students: number | null;
          payment_reference: string | null;
          auto_renew: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          plan: string;
          billing_cycle?: string | null;
          amount: number;
          currency?: string;
          start_date: string;
          end_date?: string | null;
          status?: string;
          max_students?: number | null;
          payment_reference?: string | null;
          auto_renew?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          plan?: string;
          billing_cycle?: string | null;
          amount?: number;
          currency?: string;
          start_date?: string;
          end_date?: string | null;
          status?: string;
          max_students?: number | null;
          payment_reference?: string | null;
          auto_renew?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          school_id: string;
          student_id: string;
          fee_id: string | null;
          amount: number;
          payment_method: string | null;
          payment_reference: string | null;
          receipt_number: string | null;
          paid_at: string;
          recorded_by: string | null;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          student_id: string;
          fee_id?: string | null;
          amount: number;
          payment_method?: string | null;
          payment_reference?: string | null;
          receipt_number?: string | null;
          paid_at?: string;
          recorded_by?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          student_id?: string;
          fee_id?: string | null;
          amount?: number;
          payment_method?: string | null;
          payment_reference?: string | null;
          receipt_number?: string | null;
          paid_at?: string;
          recorded_by?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      academic_terms: {
        Row: {
          id: string;
          school_id: string;
          session_id: string;
          name: string;
          term_number: number;
          start_date: string;
          end_date: string;
          is_current: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          session_id: string;
          name: string;
          term_number: number;
          start_date: string;
          end_date: string;
          is_current?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          session_id?: string;
          name?: string;
          term_number?: number;
          start_date?: string;
          end_date?: string;
          is_current?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      academic_sessions: {
        Row: {
          id: string;
          school_id: string;
          name: string;
          start_date: string;
          end_date: string;
          is_current: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          name: string;
          start_date: string;
          end_date: string;
          is_current?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          name?: string;
          start_date?: string;
          end_date?: string;
          is_current?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      assignments: {
        Row: {
          id: string;
          school_id: string;
          class_id: string;
          subject_id: string;
          teacher_id: string | null;
          academic_term_id: string | null;
          title: string;
          description: string | null;
          total_marks: number;
          due_date: string | null;
          assignment_type: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          class_id: string;
          subject_id: string;
          teacher_id?: string | null;
          academic_term_id?: string | null;
          title: string;
          description?: string | null;
          total_marks?: number;
          due_date?: string | null;
          assignment_type?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          class_id?: string;
          subject_id?: string;
          teacher_id?: string | null;
          academic_term_id?: string | null;
          title?: string;
          description?: string | null;
          total_marks?: number;
          due_date?: string | null;
          assignment_type?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      assignment_submissions: {
        Row: {
          id: string;
          school_id: string;
          assignment_id: string;
          student_id: string;
          submitted_at: string | null;
          score: number | null;
          remarks: string | null;
          attachment_url: string | null;
          status: string;
          graded_by: string | null;
          graded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          assignment_id: string;
          student_id: string;
          submitted_at?: string | null;
          score?: number | null;
          remarks?: string | null;
          attachment_url?: string | null;
          status?: string;
          graded_by?: string | null;
          graded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          assignment_id?: string;
          student_id?: string;
          submitted_at?: string | null;
          score?: number | null;
          remarks?: string | null;
          attachment_url?: string | null;
          status?: string;
          graded_by?: string | null;
          graded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};

export type School = Database['public']['Tables']['schools']['Row'];
export type Staff = Database['public']['Tables']['staff']['Row'];
export type Student = Database['public']['Tables']['students']['Row'];
export type Parent = Database['public']['Tables']['parents']['Row'];
export type Class = Database['public']['Tables']['classes']['Row'];
export type Subject = Database['public']['Tables']['subjects']['Row'];
export type Attendance = Database['public']['Tables']['attendance']['Row'];
export type Grade = Database['public']['Tables']['grades']['Row'];
export type BehaviourRecord = Database['public']['Tables']['behaviour_records']['Row'];
export type RiskAssessment = Database['public']['Tables']['risk_assessments']['Row'];
export type Intervention = Database['public']['Tables']['interventions']['Row'];
export type Notification = Database['public']['Tables']['notifications']['Row'];
export type Subscription = Database['public']['Tables']['subscriptions']['Row'];
export type Payment = Database['public']['Tables']['payments']['Row'];
export type AcademicTerm = Database['public']['Tables']['academic_terms']['Row'];
export type AcademicSession = Database['public']['Tables']['academic_sessions']['Row'];
export type Assignment = Database['public']['Tables']['assignments']['Row'];
export type AssignmentSubmission = Database['public']['Tables']['assignment_submissions']['Row'];
